name: Terraform Azure AD User

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # allows manual run

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: https://github.com/junaid-web97938/demo.git

      - name: Terraform Plan
        run: terraform plan
        working-directory: https://github.com/junaid-web97938/demo.git
        env:
          TF_VAR_tenant_id: ${{ vars.TENANT_ID }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: https://github.com/junaid-web97938/demo.git
        env:
          TF_VAR_tenant_id: ${{ vars.TENANT_ID }}